require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'db/migrate/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/InverseOf:
  Enabled: false
